name: testnet CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  redeploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies, build
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install
      - run: yarn build

      - name: Copy dist folder via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HH_HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: ".output"
          target: "stage/front"
